### ISSUE TITLE
fetch_reads does not recognize kmer in reads

### ISSUE THREAD

**Issue by renhamm** [voichek/fetch_reads_with_kmers#3]
I am trying to run fetch_reads, and despite the kmers themselves being successfully recognized by the program, it is unable to find any reads across 330 individuals that match any of my 10,001 kmers. I tested this with a toy dataset containing one 31bp kmer that lifted directly from the fastq file pair that I inputted, and it again was unable to find any reads that matched. How should I fix this? My command is below:

/path/to/fetch_reads /fastq/PEX-R1.trim.fastq /fastq/PEX-R2.trim.fastq test.fasta 31 test_reads

**Comment by renhamm** [comment]
For reference, here are the first three kmers in my R1 input fastq:

@A00887:463:HKGH5DSX3:1:1101:2266:1000 1:N:0:ATGACACC+ATATGAGA
NTATTAAAGTCATAGTATTGTAGTTCGTGTTTTTAAGAACGTTGTTGCGGATGCTTTTGCGAATTTTTTTTTACATGTACGTTTTTGTGCATGTCCATTTGAGGGAGCGTGTTTTTGCATGTTTGTCGATTTGTATTAATGTCCTAGGATT
+
#FFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFF:F:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFF:FFFFFFFFFFFFF
@A00887:463:HKGH5DSX3:1:1101:6099:1000 1:N:0:ATGACACC+ATATGAGA
NCAGTGAAGCTGGCATTGATGCCTGATGATGGACCTTCTGGAATGTTCTTTGTTAGGAAGGAAGTTTCTTCTTTTGAGGAATAATTAGTGTGGATTTTGAAAATATGTAAACTGTTTTTAGTATCTATATATAATTGGCAAGATATATAAA
+
#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFF:FFFFFFFFFFFFFFFF,FFFFF:FFFFF
@A00887:463:HKGH5DSX3:1:1101:23782:1000 1:N:0:ATGACACC+ATATGAGA
NCTGTGCAGATCGGGTCGTAGAAATGTTCGACGAAATGCTGAAAGCTGGTATAAAGCCAGACTACATAACTTTCGTCTCTGTTTTGTCTGCTTGTGGGCATACGGGGCGAGTTGATGAAGGGTTTTCTTACTTCAATTTGATGAGCGAGAG
+
#FFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

**Comment by voichek** [comment]
Can you create a small example of the 3 files and upload them so I can recreate the problem?

**Comment by renhamm** [comment]
Here are some small toy versions of each of the input files. The three 31bp kmers are all directly lifted from the reads in the paired fastq files.
[test.fasta.gz](https://github.com/voichek/fetch_reads_with_kmers/files/11425635/test.fasta.gz)
[test_R1.fastq.txt](https://github.com/voichek/fetch_reads_with_kmers/files/11425636/test_R1.fastq.txt)
[test_R2.fastq.txt](https://github.com/voichek/fetch_reads_with_kmers/files/11425637/test_R2.fastq.txt)

**Comment by voichek** [comment]
I run the program and got the 3 reads, do you get a different result?

```
./fetch_reads_with_kmers/fetch_reads ./test_R1.fastq.txt ./test_R2.fastq.txt test.fasta 31 output_test
kmer length = 31
[Insert kmers]: 3 kmers
counter = 0
[found reads]: 3 reads
```

**Comment by renhamm** [comment]
Using the exact same files, I get :
/global/home/users/laurenhamm/fetch_reads_with_kmers/fetch_reads
./test_R1.fastq.txt ./test_R2.fastq.txt test.fasta.gz 31 output_test
kmer length = 31
[Insert kmers]: 3 kmers
[found reads]: 0 reads

**Comment by voichek** [comment]
Hi,

First, it is not exactly the same because in the command line you put test.fasta.gz and I input the non-gz file. However it doesn't seem to be the issue.

Second, the problem seem to be that the program doesn't find anything in your test_R1/2..., not sure why.

Can you make sure you have the files in the same directory? I also noticed that you didn't have the "./" for the test.gasta.gz...

Best,
Yoav

**Comment by renhamm** [comment]
Updating my command with the small changes you highlighted
(/global/home/users/laurenhamm/fetch_reads_with_kmers/fetch_reads
./test_R1.fastq.txt ./test_R2.fastq.txt ./test.fasta 31 output_test), I
still get the same result. I am going to try to reinstall the fetch_reads
program, and see if that fixes anything.
Ren

**Comment by renhamm** [comment]
I have reinstalled fetch_reads_with _kmers, moved everything into one directory, unzipped my fasta file, and run the command using the same files, and I get the same result. Not sure where to go from here.
Ren

**Comment by voichek** [comment]
I am also not sure. 
I made a debug version for you with more output messages, please try it and output here what you got.
[debug_version_20230517.zip](https://github.com/voichek/fetch_reads_with_kmers/files/11499802/debug_version_20230517.zip)

**Comment by laurenhamm** [comment]
I'm not sure if I am just missing something obvious, but when I try to run the debug script, it throws a "Permission denied" error. Does this script require sudo access? I running this remotely on the university htc system, so I don't have root permissions.

**Comment by renhamm** [comment]
It seems to be running now! I think there was a weird module incompatibility loaded onto my system, but removing it seemed to fix that problem. Thanks!
