### ISSUE TITLE
map alignment positions back to GWAS outlier kmers

### ISSUE THREAD

**Issue by renhamm** [voichek/fetch_reads_with_kmers#4]
I have successfully finished this pipeline so that I have run a GWAS using gemma on each of the kmers in my dataset, fetched the reads which contain those kmers using fetch_reads_with_kmers, scaffolded them together into contigs using SPAdes, then aligned them to my reference genome using both bowtie and bwa-mem2. I now need to take these alignment locations and assign them to their original kmers so that I can map the GWAS peaks across the genome. However, I cannot figure out how to do this. 
Is there a manual resource somewhere which explains this step?

**Comment by voichek** [comment]
Hi,

The methodology we used in our paper is detailed in the Methods section, which should provide some guidance. In my experience, this step often requires some customization, so it’s not uncommon to need to experiment a bit.

If you’ve already identified k-mers with significant associations and mapped the assembled contigs to the genome, the mapping locations should guide you to the regions associated with those k-mers. 

Best,
Yoav
